<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <PlatformTarget>x64</PlatformTarget>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <GamePath>$(MSBuildThisFileDirectory)..\..\..\..\..\Stardew Valley</GamePath>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../GameAgent.Stardew.csproj" />
    <Reference Include="StardewModdingAPI" HintPath="$(GamePath)/StardewModdingAPI.dll" />
    <Reference Include="Stardew Valley" HintPath="$(GamePath)/Stardew Valley.dll" />
    <Reference Include="MonoGame.Framework" HintPath="$(GamePath)/MonoGame.Framework.dll" />
    <Reference Include="StardewValley.GameData" HintPath="$(GamePath)/StardewValley.GameData.dll" />
    <Reference Include="xTile" HintPath="$(GamePath)/xTile.dll" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.11.1" />
    <PackageReference Include="xunit" Version="2.9.2" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.8.2" PrivateAssets="All" />
  </ItemGroup>
</Project>
